name: AquaticCrates
version: '${project.version}'
main: cz.larkyy.aquaticcratestesting.AquaticCratesTesting
api-version: 1.16
commands:
  aquaticcrates:
    aliases:
      - acrates
      - aquaticcrate