name: AquaticCrates
version: '${project.version}'
main: cz.larkyy.aquaticcrates.AquaticCrates
api-version: 1.16
author: LARKYY
softdepend:
  - PlaceholderAPI
  - PlayerEmotes
  - ItemsAdder
  - ModelEngine
  - MythicMobs
  - HeadDatabase
  - AquaticModelEngine
commands:
  aquaticcrates:
    aliases:
      - acrates
      - aquaticcrate